version: "3.5"

networks:
  traefik-public:
    external: true
  monumap-production:
    external: false
  monumap-staging:
    external: false

services:
  client:
    volumes:
      - shared-volume-dev:/data/public/images:rw
    command: npm run serve
    build: 
      context: ./client      
      target: builder
    ports:
      - 8080:8080

  server:
    volumes:
      - shared-volume-dev:/tmp/images:rw
    command: npm run start:dev

    build: 
      context: ./server      
      target: builder
    env_file:
      - ./server/docker/dev.env 
volumes:
  shared-volume-dev: